on:
  push:
    paths:
      - 'yarn.lock'

jobs:
  lockfile-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SF_CLI_BOT_GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
      - run: |
          npm install -g lockfile-lint
          lockfile-lint --path yarn.lock --allowed-hosts npm yarn --validate-https
